#name, main, version and api are required
name: GameSelector
main: GameSelector\Main
version: 0.1
api: 3.0.0-ALPHA7, 3.0.1
author: EmreTr1
description: GameSelector 
commands:
 gs:
   description: GameSelector
   
